now looking for ruby modules in only one location

diff --git a/omf-expctl/bin/omf-expctl b/omf-expctl/bin/omf-expctl
--- a/omf-expctl/bin/omf-expctl
+++ b/omf-expctl/bin/omf-expctl
@@ -25,14 +25,10 @@
 #
 
 APP=omf-expctl/handler.rb
-if [ -e ../$APP ]; then
-   PDIR=..
-else 
-   if [ -e /usr/lib/ruby/1.8/$APP ]; then
-      PDIR=/usr/lib/ruby/1.8
-   else
-      echo "Cannot find the ruby module location ($APP)."
-      exit 1;
-   fi
+if [ -e /usr/lib/ruby/1.8/$APP ]; then
+   PDIR=/usr/lib/ruby/1.8
+else
+   echo "Cannot find the ruby module $APP"
+   exit 1;
 fi
 exec ruby1.8 -I$PDIR $PDIR/$APP $*
diff --git a/omf-expctl/bin/omf_stat b/omf-expctl/bin/omf_stat
--- a/omf-expctl/bin/omf_stat
+++ b/omf-expctl/bin/omf_stat
@@ -1,3 +1,4 @@
+
 #!/bin/bash -f
 #
 # Copyright (c) 2006-2009 National ICT Australia (NICTA), Australia
@@ -79,14 +80,11 @@ if [ -z $domain ] ; then
   domain="default"
 fi
 
-if [ -e ../$APP ]; then
-   PDIR=..
-else 
-   if [ -e /usr/lib/ruby/1.8/$APP ]; then
-      PDIR=/usr/lib/ruby/1.8
-   else
-      echo "Cannot find the ruby module location ($APP)."
-      exit 1;
-   fi
+if [ -e /usr/lib/ruby/1.8/$APP ]; then
+  PDIR=/usr/lib/ruby/1.8
+else
+  echo "Cannot find the ruby module $APP"
+  exit 1;
 fi
+   
 exec ruby1.8 -I$PDIR $PDIR/$APP "[$topo_or_cmd]" $domain
