renaming debian packages (Feature #215), 3rd part, also fixing r300 checkin (missing file)

diff --git a/omf-expctl/bin/omf_save b/omf-expctl/bin/omf_save
--- a/omf-expctl/bin/omf_save
+++ b/omf-expctl/bin/omf_save
@@ -52,6 +52,11 @@ if [ $# -lt 1 ] ; then
   usage ; exit 1
 fi
 
+if [ $USER == 'root' ] ; then
+  echo "You cannot save images as superuser (root). Exiting."
+  exit 1
+fi
+
 function saveimage()
 {
   OMF=omf
